source 'http://rubygems.org'

gem 'rails', '3.2.3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'json'
gem 'twitter', '2.0.2'

# START:therubyrhino  
platform :jruby do
  gem 'therubyrhino'
  # END:therubyrhino
  # START:get_back
  gem 'get_back'
  # END:get_back
  # START:jruby_openssl
  gem 'jruby-openssl'
  # END:jruby_openssl
  # START:therubyrhino  
end
# END:therubyrhino

# START:torquebox_no_op
group :test do
  gem 'rspec-rails'
  gem 'torquebox-no-op', '2.0.2'
end
# END:torquebox_no_op

# START:db_driver
gem 'activerecord-jdbc-adapter', :require => false

# START:production
group :production do
  gem 'jdbc-postgres'
end
# END:production

group :development, :test do
  gem 'jdbc-sqlite3'
end
# END:db_driver

gem "net-ssh"
gem "net-scp"

# START:torquebox_remote_deployer
gem 'torquebox-remote-deployer', '0.1.1'
# END:torquebox_remote_deployer

# START:group_dev_prod
group :development, :production do
  gem 'torquebox-rake-support', '2.0.2'
  gem 'torquebox', '2.0.2'
end
# END:group_dev_prod
