source 'http://rubygems.org'

gem 'rails', '3.2.3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'json'
gem 'twitter', '2.0.2'

# START:therubyrhino  
platform :jruby do
  gem 'therubyrhino'
  # END:therubyrhino
  # START:get_back
  gem 'get_back'
  # END:get_back
  # START:jruby_openssl
  gem 'jruby-openssl'
  # END:jruby_openssl
end
# END:therubyrhino

group :deploy do
  gem "warbler"
end

group :test do
  gem 'rspec-rails'
end

# START:db_driver
gem 'activerecord-jdbc-adapter', :require => false

# START:production
group :production do
  gem 'jdbc-mysql'
end
# END:production

group :development, :test do
  gem 'jdbc-sqlite3'
end
# END:db_driver

# START:capistrano
gem 'capistrano'
gem 'ffi-ncurses'
# END:capistrano

# START:trinidad
gem 'trinidad', '1.3.4'
# END:trinidad
# START:trinidad_diagnostics_extension
gem 'trinidad_diagnostics_extension'
# END:trinidad_diagnostics_extension
# START:trinidad_scheduler_extension
gem 'trinidad_scheduler_extension'
# END:trinidad_scheduler_extension
# START:trinidad_resque_extension
gem 'trinidad_resque_extension'
# END:trinidad_resque_extension
# START:trinidad_sandbox_extension
gem 'trinidad_sandbox_extension'
# END:trinidad_sandbox_extension
